188633 fix cash basket entitlement
openspp-project/openspp-program pull request #42
Opened 2023-02-17 07:53 UTC by reichie020212

2023-02-20 02:26 UTC, nhatnm0612 commented on g2p_entitlement_cash/models/entitlement_manager.py
> +        return
```suggestion
        if cycle.validate_async_err:
            msg = _("Entitlements are not approved due to some issues. Kindly address the issue.")
        return super(). mark_job_as_done(cycle, msg)
```
I think this will made the code more readable

2023-02-21 00:40 UTC, gonzalesedwin1123 requested changes

2023-02-21 00:40 UTC, gonzalesedwin1123 commented on g2p_entitlement_cash/models/entitlement_manager.py
> +        return
I agree with @nhatnm0612

2023-02-21 06:59 UTC, gonzalesedwin1123 approved these changes

2023-02-21 14:33 UTC, nhatnm0612 approved these changes

2023-02-22 01:17 UTC, merged