Hide or Show prepare entitlement button based on conditions
openspp-project/openspp-program pull request #43
Opened 2023-02-20 05:02 UTC by reichie020212

2023-02-20 08:05 UTC, nhatnm0612 commented on spp_programs/models/cycle.py
> +        action = super().copy_beneficiaries_from_program()
@reichie020212 I really don't like the method. This is an action button. What will happened if this button never pressed? The `Prepare Entitlement` button will never reappeared? But when I look at your ticket, I really don't like the ticket as well 🙄 an since the PR will solve ticket the exact way suggested in ticket, I think you should move this to `pds_spp` repo, create a new module and let this stuff stay in that module only. Anyway, approve this, but this is serious, you should think about it.

2023-02-20 08:05 UTC, nhatnm0612 approved these changes

2023-02-21 00:34 UTC, gonzalesedwin1123 requested changes

2023-02-21 00:34 UTC, gonzalesedwin1123 commented on spp_programs/models/cycle.py
> +        self.write({"hide_prepare_entitlement_button": True})
@reichie020212 When job queue is used in preparing entitlements set the `hide_prepare_entitlement_button` to True to prevent the re-clicking of the button while the tasks are being performed. Add in the `job queue on_done` function  a check if all beneficiaries are generated with entitlements. Set the `hide_prepare_entitlement_button` to False if not all beneficiaries are generated with entitlements.

For non-job queue entitlement preparation, check also if all beneficiaries are generated with entitlements and set the `hide_prepare_entitlement_button` appropriately.

2023-02-21 01:56 UTC, reichie020212 commented on spp_programs/models/cycle.py
> +        action = super().copy_beneficiaries_from_program()
Hi @nhatnm0612 , The Prepare Entitlement is visible in default and will be invisible once clicked, then that button will reappear/visible again if the copy beneficary from program button will be click that's why I only added self.write({"hide_prepare_entitlement_button": False}) in this function

2023-02-22 00:16 UTC, gonzalesedwin1123 approved these changes

2023-02-22 00:41 UTC, merged