Fix error in in-kind entitlement cancellation and deleting multiple entitlements
openspp-project/openspp-program pull request #79
Opened 2023-05-24 07:48 UTC by gonzalesedwin1123

This PR provides the following fixes:
- Error when cancelling in-kind entitlements.
- Error when deleting multiple entitlements.

2023-05-24 07:57 UTC, nhatnm0612 approved these changes

2023-05-30 01:39 UTC, jeremi requested changes

2023-05-30 01:39 UTC, jeremi commented on spp_entitlement_in_kind/models/entitlement_manager.py
> +        entitlements_count = len(entitlements)
Why do this, if we have millions of entitlement this will explode the memory and will be slow. Best to do the count query and get the entitlements after if needed

2023-05-30 01:39 UTC, jeremi commented
Also make sure to add tests

2023-06-05 06:47 UTC, gonzalesedwin1123 commented on spp_entitlement_in_kind/models/entitlement_manager.py
> +        entitlements_count = len(entitlements)
Yes @jeremi, I will fix this

2023-06-22 03:44 UTC, merged